#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn prettier --check .
# Ignore:
# * 'react-instantsearch-hooks-web', because there's some bug where
#   check-peer-dependencies doesn't recognize it's installed.
# * 'ts-node', because it looks like a misdeclaration of a dependency in one of
#   our dependencies.
yarn check-peer-dependencies --ignore='react-instantsearch-hooks-web' \
                             --ignore='ts-node'
yarn lint
yarn e2e:headless
