# Checks if there are unmet peer dependencies.
#
# [Peer dependencies need to be installed
# manually](https://stackoverflow.com/questions/35738346/how-do-i-fix-the-npm-unmet-peer-dependency-warning).
name: Check peer dependencies
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn install
      - name: Check peer dependencies
        # See .husky/pre-commit for comments
        run: yarn check-peer-dependencies --ignore='react-instantsearch-hooks-web' --ignore='ts-node'
