name: Run e2e tests
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn dev --port 3003
