name: Run e2e tests
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn install
      - run: yarn e2e:headless
